### ISSUE TITLE
Consider CSS rules to identify widgets missing configuration options

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Widgets#217]
As in

```css
img[alt=""], img:not([alt]) {
    border: dashed 5px red;
}
```
